version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
