/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ["react-form-fields"],
  rules: {
    "react-form-fields/example-rule": "error"
  },
};
