/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ['react-form-fields'],
  rules: {
    'react-form-fields/no-mix-controlled-with-uncontrolled': 'error',
    'react-form-fields/no-only-value-prop': 'error',
  },
};
