/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

export = {
  configs: {
    recommended: import('./configs/recommended'),
  },
  rules: {
    'no-mix-controlled-with-uncontrolled': import(
      './rules/no-mix-controlled-with-uncontrolled'
    ),
    'no-only-value-prop': import('./rules/no-only-value-prop'),
  },
};
