/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

export = {
  configs: {
    recommended: require('./configs/recommended'),
  },
  rules: {
    'no-mix-controlled-with-uncontrolled': require('./rules/no-mix-controlled-with-uncontrolled'),
    'no-only-value-prop': require('./rules/no-only-value-prop'),
    'styled-no-mix-controlled-with-uncontrolled': require('./rules/styled-no-mix-controlled-with-uncontrolled'),
    'styled-no-only-value-prop': require('./rules/styled-no-only-value-prop'),
  },
};
