/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { TSESLint } from '@typescript-eslint/experimental-utils';
import recommended from './configs/recommended';
import noMixControlledWithUncontrolled from './rules/no-mix-controlled-with-uncontrolled';
import noOnlyValueProp from './rules/no-only-value-prop';
import styledNoMixControlledWithUncontrolled from './rules/styled-no-mix-controlled-with-uncontrolled';
import styledNoOnlyValueProp from './rules/styled-no-only-value-prop';

export const configs: TSESLint.Linter.Plugin['configs'] = {
  recommended,
};

export const rules: TSESLint.Linter.Plugin['rules'] = {
  'no-mix-controlled-with-uncontrolled': noMixControlledWithUncontrolled,
  'no-only-value-prop': noOnlyValueProp,
  'styled-no-mix-controlled-with-uncontrolled':
    styledNoMixControlledWithUncontrolled,
  'styled-no-only-value-prop': styledNoOnlyValueProp,
};
