name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        eslint-version: [5, 6, 7, 8]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Install ESLint v${{ matrix.eslint-version }}
        run: npm install --no-save --force eslint@${{ matrix.eslint-version }}
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Build
        run: npm run build
